targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/models/*.dart
          exclude:
            - lib/models/*freezed.dart
      json_serializable:
        generate_for:
          include:
            - lib/models/*.dart
          exclude:
            - lib/models/*freezed.dart
        options:
          any_map: true
          explicit_to_json: true